In [2]:
install.packages("tidyverse", repos="https://cloud.r-project.org/")

Installing package into 'C:/Users/mmice/AppData/Local/R/win-library/4.4'
(as 'lib' is unspecified)

also installing the dependencies 'colorspace', 'sys', 'bit', 'ps', 'sass', 'cachem', 'farver', 'labeling', 'munsell', 'RColorBrewer', 'viridisLite', 'rappdirs', 'rematch', 'askpass', 'bit64', 'prettyunits', 'processx', 'highr', 'xfun', 'yaml', 'bslib', 'fontawesome', 'jquerylib', 'tinytex', 'backports', 'generics', 'memoise', 'blob', 'DBI', 'R6', 'tidyselect', 'withr', 'data.table', 'gtable', 'isoband', 'scales', 'gargle', 'cellranger', 'curl', 'ids', 'rematch2', 'cpp11', 'pkgconfig', 'mime', 'openssl', 'timechange', 'systemfonts', 'textshaping', 'clipr', 'vroom', 'tzdb', 'progress', 'callr', 'fs', 'knitr', 'rmarkdown', 'selectr', 'stringi', 'fansi', 'broom', 'conflicted', 'dbplyr', 'dplyr', 'dtplyr', 'forcats', 'ggplot2', 'googledrive', 'googlesheets4', 'haven', 'hms', 'httr', 'lubridate', 'magrittr', 'modelr', 'purrr', 'ragg', 'readr', 'readxl', 'reprex', 'rstudioapi', 'rvest', 'stringr', 'tibble', 'tidyr', 'xml2'

package 'colorspace' successfully unpacked and MD5 sums checked
package 'sys' successfully unpacked and MD5 sums checked
package 'bit' successfully unpacked and MD5 sums checked
package 'ps' successfully unpacked and MD5 sums checked
package 'sass' successfully unpacked and MD5 sums checked
package 'cachem' successfully unpacked and MD5 sums checked
package 'farver' successfully unpacked and MD5 sums checked
package 'labeling' successfully unpacked and MD5 sums checked
package 'munsell' successfully unpacked and MD5 sums checked
package 'RColorBrewer' successfully unpacked and MD5 sums checked
package 'viridisLite' successfully unpacked and MD5 sums checked
package 'rappdirs' successfully unpacked and MD5 sums checked
package 'rematch' successfully unpacked and MD5 sums checked
package 'askpass' successfully unpacked and MD5 sums checked
package 'bit64' successfully unpacked and MD5 sums checked
package 'prettyunits' successfully unpacked and MD5 sums checked
package 'processx' successfully unpacked and MD5 sums checked
package 'highr' successfully unpacked and MD5 sums checked
package 'xfun' successfully unpacked and MD5 sums checked
package 'yaml' successfully unpacked and MD5 sums checked
package 'bslib' successfully unpacked and MD5 sums checked
package 'fontawesome' successfully unpacked and MD5 sums checked
package 'jquerylib' successfully unpacked and MD5 sums checked
package 'tinytex' successfully unpacked and MD5 sums checked
package 'backports' successfully unpacked and MD5 sums checked
package 'generics' successfully unpacked and MD5 sums checked
package 'memoise' successfully unpacked and MD5 sums checked
package 'blob' successfully unpacked and MD5 sums checked
package 'DBI' successfully unpacked and MD5 sums checked
package 'R6' successfully unpacked and MD5 sums checked
package 'tidyselect' successfully unpacked and MD5 sums checked
package 'withr' successfully unpacked and MD5 sums checked
package 'data.table' successfully unpacked and MD5 sums checked
package 'gtable' successfully unpacked and MD5 sums checked
package 'isoband' successfully unpacked and MD5 sums checked
package 'scales' successfully unpacked and MD5 sums checked
package 'gargle' successfully unpacked and MD5 sums checked
package 'cellranger' successfully unpacked and MD5 sums checked
package 'curl' successfully unpacked and MD5 sums checked
package 'ids' successfully unpacked and MD5 sums checked
package 'rematch2' successfully unpacked and MD5 sums checked
package 'cpp11' successfully unpacked and MD5 sums checked
package 'pkgconfig' successfully unpacked and MD5 sums checked
package 'mime' successfully unpacked and MD5 sums checked
package 'openssl' successfully unpacked and MD5 sums checked
package 'timechange' successfully unpacked and MD5 sums checked
package 'systemfonts' successfully unpacked and MD5 sums checked
package 'textshaping' successfully unpacked and MD5 sums checked
package 'clipr' successfully unpacked and MD5 sums checked
package 'vroom' successfully unpacked and MD5 sums checked
package 'tzdb' successfully unpacked and MD5 sums checked
package 'progress' successfully unpacked and MD5 sums checked
package 'callr' successfully unpacked and MD5 sums checked
package 'fs' successfully unpacked and MD5 sums checked
package 'knitr' successfully unpacked and MD5 sums checked
package 'rmarkdown' successfully unpacked and MD5 sums checked
package 'selectr' successfully unpacked and MD5 sums checked
package 'stringi' successfully unpacked and MD5 sums checked
package 'fansi' successfully unpacked and MD5 sums checked
package 'broom' successfully unpacked and MD5 sums checked
package 'conflicted' successfully unpacked and MD5 sums checked
package 'dbplyr' successfully unpacked and MD5 sums checked
package 'dplyr' successfully unpacked and MD5 sums checked
package 'dtplyr' successfully unpacked and MD5 sums checked
package 'forcats' successfully unpacked and MD5 sums checked
package 'ggplot2' successfully unpacked and MD5 sums checked
package 'googledrive' successfully unpacked and MD5 sums checked
package 'googlesheets4' successfully unpacked and MD5 sums checked
package 'haven' successfully unpacked and MD5 sums checked
package 'hms' successfully unpacked and MD5 sums checked
package 'httr' successfully unpacked and MD5 sums checked
package 'lubridate' successfully unpacked and MD5 sums checked
package 'magrittr' successfully unpacked and MD5 sums checked
package 'modelr' successfully unpacked and MD5 sums checked
package 'purrr' successfully unpacked and MD5 sums checked
package 'ragg' successfully unpacked and MD5 sums checked
package 'readr' successfully unpacked and MD5 sums checked
package 'readxl' successfully unpacked and MD5 sums checked
package 'reprex' successfully unpacked and MD5 sums checked
package 'rstudioapi' successfully unpacked and MD5 sums checked
package 'rvest' successfully unpacked and MD5 sums checked
package 'stringr' successfully unpacked and MD5 sums checked
package 'tibble' successfully unpacked and MD5 sums checked
package 'tidyr' successfully unpacked and MD5 sums checked
package 'xml2' successfully unpacked and MD5 sums checked
package 'tidyverse' successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\mmice\AppData\Local\Temp\RtmpKcMdwK\downloaded_packages

In [3]:
### It's always a good idea when working in RStudio to start with a clean environment. 
### Clear objects from the environment memory that may be leftover from previous versions of your code or other assignments by running the following line:
rm(list = ls())

### Load Libraries
library(tidyverse)

── Attaching core tidyverse packages ──────────────────────────────────────────────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.5
✔ forcats   1.0.0     ✔ stringr   1.5.1
✔ ggplot2   3.5.1     ✔ tibble    3.2.1
✔ lubridate 1.9.4     ✔ tidyr     1.3.1
✔ purrr     1.0.4
── Conflicts ────────────────────────────────────────────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

In [5]:
msleep

   name                           genus         vore    order
1  Cheetah                        Acinonyx      carni   Carnivora
2  Owl monkey                     Aotus         omni    Primates
3  Mountain beaver                Aplodontia    herbi   Rodentia
4  Greater short-tailed shrew     Blarina       omni    Soricomorpha
5  Cow                            Bos           herbi   Artiodactyla
6  Three-toed sloth               Bradypus      herbi   Pilosa
7  Northern fur seal              Callorhinus   carni   Carnivora
8  Vesper mouse                   Calomys       NA      Rodentia
9  Dog                            Canis         carni   Carnivora
10 Roe deer                       Capreolus     herbi   Artiodactyla
11 Goat                           Capri         herbi   Artiodactyla
12 Guinea pig                     Cavis         herbi   Rodentia
13 Grivet                         Cercopithecus omni    Primates
14 Chinchilla                     Chinchilla    herbi   Rodentia
15 Star-nosed mole                Condylura     omni    Soricomorpha
16 African giant pouched rat      Cricetomys    omni    Rodentia
17 Lesser short-tailed shrew      Cryptotis     omni    Soricomorpha
18 Long-nosed armadillo           Dasypus       carni   Cingulata
19 Tree hyrax                     Dendrohyrax   herbi   Hyracoidea
20 North American Opossum         Didelphis     omni    Didelphimorphia
21 Asian elephant                 Elephas       herbi   Proboscidea
22 Big brown bat                  Eptesicus     insecti Chiroptera
23 Horse                          Equus         herbi   Perissodactyla
24 Donkey                         Equus         herbi   Perissodactyla
25 European hedgehog              Erinaceus     omni    Erinaceomorpha
26 Patas monkey                   Erythrocebus  omni    Primates
27 Western american chipmunk      Eutamias      herbi   Rodentia
28 Domestic cat                   Felis         carni   Carnivora
29 Galago                         Galago        omni    Primates
30 Giraffe                        Giraffa       herbi   Artiodactyla
⋮  ⋮                              ⋮             ⋮       ⋮
54 Baboon                         Papio         omni    Primates
55 Desert hedgehog                Paraechinus   NA      Erinaceomorpha
56 Potto                          Perodicticus  omni    Primates
57 Deer mouse                     Peromyscus    NA      Rodentia
58 Phalanger                      Phalanger     NA      Diprotodontia
59 Caspian seal                   Phoca         carni   Carnivora
60 Common porpoise                Phocoena      carni   Cetacea
61 Potoroo                        Potorous      herbi   Diprotodontia
62 Giant armadillo                Priodontes    insecti Cingulata
63 Rock hyrax                     Procavia      NA      Hyracoidea
64 Laboratory rat                 Rattus        herbi   Rodentia
65 African striped mouse          Rhabdomys     omni    Rodentia
66 Squirrel monkey                Saimiri       omni    Primates
67 Eastern american mole          Scalopus      insecti Soricomorpha
68 Cotton rat                     Sigmodon      herbi   Rodentia
69 Mole rat                       Spalax        NA      Rodentia
70 Arctic ground squirrel         Spermophilus  herbi   Rodentia
71 Thirteen-lined ground squirrel Spermophilus  herbi   Rodentia
72 Golden-mantled ground squirrel Spermophilus  herbi   Rodentia
73 Musk shrew                     Suncus        NA      Soricomorpha
74 Pig                            Sus           omni    Artiodactyla
75 Short-nosed echidna            Tachyglossus  insecti Monotremata
76 Eastern american chipmunk      Tamias        herbi   Rodentia
77 Brazilian tapir                Tapirus       herbi   Perissodactyla
78 Tenrec                         Tenrec        omni    Afrosoricida
79 Tree shrew                     Tupaia        omni    Scandentia
80 Bottle-nosed dolphin           Tursiops      carni   Cetacea
81 Genet                          Genetta       carni   Carnivora
82 Arctic fox                     Vulpes        carni   Carnivora
83 Red fox                        Vulpes        carni   Carnivora
   conservation sleep_total sleep_rem sleep_cycle awake brainwt bodywt
1  lc           12.1         NA              NA   11.9       NA   50.000
2  NA           17.0        1.8              NA    7.0  0.01550    0.480
3  nt           14.4        2.4              NA    9.6       NA    1.350
4  lc           14.9        2.3       0.1333333    9.1  0.00029    0.019
5  domesticated  4.0        0.7       0.6666667   20.0  0.42300  600.000
6  NA           14.4        2.2       0.7666667    9.6       NA    3.850
7  vu            8.7        1.4       0.3833333   15.3       NA   20.490
8  NA            7.0         NA              NA   17.0       NA    0.045
9  domesticated 10.1        2.9       0.3333333   13.9  0.07000   14.000
10 lc            3.0         NA              NA   21.0  0.09820   14.800
11 lc            5.3        0.6              NA   18.7  0.11500   33.500
12 domesticated  9.4        0.8       0.2166667   14.6  0.00550    0.728
13 lc           10.0        0.7              NA   14.0       NA    4.750
14 domesticated 12.5        1.5       0.1166667   11.5  0.00640    0.420
15 lc           10.3        2.2              NA   13.7  0.00100    0.060
16 NA            8.3        2.0              NA   15.7  0.00660    1.000
17 lc            9.1        1.4       0.1500000   14.9  0.00014    0.005
18 lc           17.4        3.1       0.3833333    6.6  0.01080    3.500
19 lc            5.3        0.5              NA   18.7  0.01230    2.950
20 lc           18.0        4.9       0.3333333    6.0  0.00630    1.700
21 en            3.9         NA              NA   20.1  4.60300 2547.000
22 lc           19.7        3.9       0.1166667    4.3  0.00030    0.023
23 domesticated  2.9        0.6       1.0000000   21.1  0.65500  521.000
24 domesticated  3.1        0.4              NA   20.9  0.41900  187.000
25 lc           10.1        3.5       0.2833333   13.9  0.00350    0.770
26 lc           10.9        1.1              NA   13.1  0.11500   10.000
27 NA           14.9         NA              NA    9.1       NA    0.071
28 domesticated 12.5        3.2       0.4166667   11.5  0.02560    3.300
29 NA            9.8        1.1       0.5500000   14.2  0.00500    0.200
30 cd            1.9        0.4              NA   22.1       NA  899.995
⋮  ⋮            ⋮           ⋮         ⋮           ⋮     ⋮       ⋮
54 NA            9.4        1.0       0.6666667   14.60 0.18000  25.235
55 lc           10.3        2.7              NA   13.70 0.00240   0.550
56 lc           11.0         NA              NA   13.00      NA   1.100
57 NA           11.5         NA              NA   12.50      NA   0.021
58 NA           13.7        1.8              NA   10.30 0.01140   1.620
59 vu            3.5        0.4              NA   20.50      NA  86.000
60 vu            5.6         NA              NA   18.45      NA  53.180
61 NA           11.1        1.5              NA   12.90      NA   1.100
62 en           18.1        6.1              NA    5.90 0.08100  60.000
63 lc            5.4        0.5              NA   18.60 0.02100   3.600
64 lc           13.0        2.4       0.1833333   11.00 0.00190   0.320
65 NA            8.7         NA              NA   15.30      NA   0.044
66 NA            9.6        1.4              NA   14.40 0.02000   0.743
67 lc            8.4        2.1       0.1666667   15.60 0.00120   0.075
68 NA           11.3        1.1       0.1500000   12.70 0.00118   0.148
69 NA           10.6        2.4              NA   13.40 0.00300   0.122
70 lc           16.6         NA              NA    7.40 0.00570   0.920
71 lc           13.8        3.4       0.2166667   10.20 0.00400   0.101
72 lc           15.9        3.0              NA    8.10      NA   0.205
73 NA           12.8        2.0       0.1833333   11.20 0.00033   0.048
74 domesticated  9.1        2.4       0.5000000   14.90 0.18000  86.250
75 NA            8.6         NA              NA   15.40 0.02500   4.500
76 NA           15.8         NA              NA    8.20      NA   0.112
77 vu            4.4        1.0       0.9000000   19.60 0.16900 207.501
78 NA           15.6        2.3              NA    8.40 0.00260   0.900
79 NA            8.9        2.6       0.2333333   15.10 0.00250   0.104
80 NA            5.2         NA              NA   18.80      NA 173.330
81 NA            6.3        1.3              NA   17.70 0.01750   2.000
82 NA           12.5         NA              NA   11.50 0.04450   3.380
83 NA            9.8        2.4       0.3500000   14.20 0.05040   4.230

## Dataframe manipulation with R

In [8]:
#Creating a dataframe with only name and bodyweight, arranged by bodyweight in highest to lowest order

Q1 <- msleep |>
  select(name, bodywt) |>
  arrange(desc(bodywt)) |>
  as.data.frame()

Q1

   name                           bodywt
1  African elephant               6654.000
2  Asian elephant                 2547.000
3  Giraffe                         899.995
4  Pilot whale                     800.000
5  Cow                             600.000
6  Horse                           521.000
7  Brazilian tapir                 207.501
8  Donkey                          187.000
9  Bottle-nosed dolphin            173.330
10 Tiger                           162.564
11 Lion                            161.499
12 Jaguar                          100.000
13 Pig                              86.250
14 Caspian seal                     86.000
15 Gray seal                        85.000
16 Human                            62.000
17 Giant armadillo                  60.000
18 Sheep                            55.500
19 Common porpoise                  53.180
20 Chimpanzee                       52.200
21 Cheetah                          50.000
22 Goat                             33.500
23 Baboon                           25.235
24 Northern fur seal                20.490
25 Roe deer                         14.800
26 Dog                              14.000
27 Patas monkey                     10.000
28 Macaque                           6.800
29 Grivet                            4.750
30 Short-nosed echidna               4.500
⋮  ⋮                              ⋮
54 Desert hedgehog                0.550
55 Owl monkey                     0.480
56 Chinchilla                     0.420
57 Thick-tailed opposum           0.370
58 Laboratory rat                 0.320
59 Round-tailed muskrat           0.266
60 Degu                           0.210
61 Golden-mantled ground squirrel 0.205
62 Galago                         0.200
63 Cotton rat                     0.148
64 Mole rat                       0.122
65 Golden hamster                 0.120
66 Eastern american chipmunk      0.112
67 Tree shrew                     0.104
68 Thirteen-lined ground squirrel 0.101
69 Eastern american mole          0.075
70 Western american chipmunk      0.071
71 Star-nosed mole                0.060
72 Mongolian gerbil               0.053
73 Musk shrew                     0.048
74 Vesper mouse                   0.045
75 African striped mouse          0.044
76 Vole                           0.035
77 Northern grasshopper mouse     0.028
78 Big brown bat                  0.023
79 House mouse                    0.022
80 Deer mouse                     0.021
81 Greater short-tailed shrew     0.019
82 Little brown bat               0.010
83 Lesser short-tailed shrew      0.005

In [10]:
#Finding the animal with the highest bodyweight

Q3 <- msleep |>
  select(name, bodywt) |>
  arrange(desc(bodywt)) |>
  select(name) |>
  slice_head(n=1) |>
  as.data.frame()
  
Q3

  name
1 African elephant

In [11]:
#Finding the animal with the lowest brainweight

Q4 <- msleep |>
  select(name, brainwt) |>
  arrange(brainwt) |>
  select(name) |>
  slice_head(n=1) |>
  as.data.frame()




### VIEW OUTPUT ###
Q4

  name
1 Lesser short-tailed shrew

In [12]:
#Creating a dataframe and sorting by genus while also filtering for only primates

Q5 <- msleep |>
  filter(order == "Primates") |>
  select(genus, name, order) |>
  arrange(genus) |>
  as.data.frame()

Q5

   genus         name            order
1  Aotus         Owl monkey      Primates
2  Cercopithecus Grivet          Primates
3  Erythrocebus  Patas monkey    Primates
4  Galago        Galago          Primates
5  Homo          Human           Primates
6  Lemur         Mongoose lemur  Primates
7  Macaca        Macaque         Primates
8  Nyctibeus     Slow loris      Primates
9  Pan           Chimpanzee      Primates
10 Papio         Baboon          Primates
11 Perodicticus  Potto           Primates
12 Saimiri       Squirrel monkey Primates

In [13]:
#Filtering a dataframe for only carnivores with the conservation status of LC and calculating the variance in total sleep

Q6 <- msleep |>
  filter(vore == "carni" & conservation == "lc") |>
  group_by(vore) |>
  summarise(var = round(var(sleep_total),2)) |>
  select(var) |>
  as.data.frame()

Q6

  var
1 26.35

In [14]:
#Filtering for rodent with the highest ratio of sleep to REM sleep

Q7 <- msleep |>
  filter(order == "Rodentia") |>
  mutate(sleep_ratio = sleep_total/sleep_rem) |>
  slice_max(sleep_ratio, n=1) |>
  select(name) |>
  as.data.frame()

Q7

  name
1 Guinea pig

In [15]:
#Finding how many primates have a bodyweight to brain weight ratio greater than 100

Q8 <- msleep |>
  filter(order == "Primates") |>
  mutate(brain_body_ratio = bodywt/brainwt) |>
  filter(brain_body_ratio > 100)|>
  count() |>
  as.data.frame()

Q8

  n
1 3

In [ ]:
#Removing missing values, and finding the mean sleep and variance of sleep group

Q9 <- msleep |>
  filter(conservation != "NA") |>
  group_by(conservation) |>
  summarise(mean_sleep = round(mean(sleep_total, na.rm=TRUE),2),
            var_sleep = round(var(sleep_total, na.rm=TRUE),2)) |>
  as.data.frame()

Q9